<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\sun.ico</ApplicationIcon>
    <Platforms>x64</Platforms>

    <ApplicationManifest>app.manifest</ApplicationManifest>

    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>

    <Product>HdrTracer</Product>
    <AssemblyTitle>HdrTracer</AssemblyTitle>
    <Description>NTFS 파일 검색 도구</Description>
    <Company>HaeDream</Company>
    <Copyright>Copyright © 2026</Copyright>
    <Version>1.3.0</Version>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>

    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\sun.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HdrTracer.Core\HdrTracer.Core.csproj" />
  </ItemGroup>
</Project>
